version: '3.4'

services:  
  nginxedclient:
    image: ${DOCKER_REGISTRY-}wizard.client
    ports:
      - "8080:80"
    networks:
      - net1
    build:
      context: ./src/Wizard.Client
      dockerfile: Dockerfile
      
  webapiservice:
    image: ${DOCKER_REGISTRY-}wizard.api
    container_name: 'webapi'
    ports:
        - "5678:80"
    depends_on:
      - "postgres"
    networks:
      - net1
#    restart: on-failure
    build:
      context: .
      dockerfile: src/Wizard.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      
  postgres:
    container_name: 'postgres'
    image: postgres:latest
    networks:
      - net1
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
        - "5432:5432"

networks:
  net1:
    driver: bridge
